### ISSUE TITLE
Add to Addon Manager?

### ISSUE THREAD

**Issue by luzpaz** [looooo/freecad.frametools#9]
@looooo what say you?

**Comment by looooo** [comment]
sure, I see it already in the add-on-manager. package.xml was added. Not sure if anything is missing.

**Comment by luzpaz** [comment]
Sorry, it's named differently on there.

**Comment by looooo** [comment]
can we change the name? I would like to call it freecad.frametools if possible.

**Comment by looooo** [comment]
same for the gears workbench. would be nice to call it freecad.gears.

**Comment by luzpaz** [comment]
@chennes Would i tbe ok to rename said workbenches?

**Comment by chennes** [comment]
You can specify literally any text you like as the "name" in package.xml, and that's what will be displayed by the Addon Manager. It just has to be unique. It's cached locally, so users won't see an update until their cache refreshes.

**Comment by ghost** [comment]
It seems like frame workbench actually provided by FreeCAD "Addon Manager" is outdated or even broken:

- https://github.com/FreeCAD/FreeCAD-addons/tree/master
  - https://github.com/looooo/freecad_frame/tree/11bd2189ef7e757be503eb5c12b35a50797bcf7a

Need to review it status and update to `master`:

- https://github.com/FreeCAD/FreeCAD-addons/issues/200
  - https://github.com/looooo/freecad_frame/tree/master

Actually provided "frame.freecad workbench" failed to loads in FreeCAD Addon Manager and tries to load `README.md` in the branch that does not exists:

- https://github.com/looooo/freecad.frametools/blob/develop/README.md

![Screenshot_2023-03-18_15-59-58](https://user-images.githubusercontent.com/13188580/226110784-16ea41c6-9d61-4e6e-bc7b-6ddec5208dc1.png)

![Screenshot_2023-03-18_16-00-12](https://user-images.githubusercontent.com/13188580/226110787-5a613458-63b9-4f30-8e0c-a93989f408eb.png)
